### ISSUE TITLE
Simplificaciones 

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-nestor-diego-elisa#1]
[simplificaciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-nestor-diego-elisa/files/13621403/simplificaciones.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
